### ISSUE TITLE
Memcached and serialization of RegexMatchingRegisteredServiceProxyPolicy

### ISSUE THREAD

**Issue by smicyk** [Jasig/cas#1362]
Hi,

I have configured memcached as ticketRegistry but when I want to use it, I get serialization exception of `RegexMatchingRegisteredServiceProxyPolicy` object. Here is part of the stacktrace:

```
Caused by: java.util.concurrent.ExecutionException: com.esotericsoftware.kryo.KryoException: Class cannot be created (missing no-arg constructor): java.util.regex.Pattern
Serialization trace:
pattern (org.jasig.cas.services.RegexMatchingRegisteredServiceProxyPolicy)
proxyPolicy (com.arkena.acas.services.AuthorizationBasedRegexRegisteredService)
service (org.jasig.cas.authentication.HttpBasedServiceCredential)
credentialMetaData (org.jasig.cas.authentication.DefaultHandlerResult)
successes (org.jasig.cas.authentication.ImmutableAuthentication)
authentication (org.jasig.cas.ticket.TicketGrantingTicketImpl)
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:188)
	at net.spy.memcached.transcoders.TranscodeService$Task.get(TranscodeService.java:97)
	at net.spy.memcached.internal.GetFuture.get(GetFuture.java:70)
	at net.spy.memcached.MemcachedClient.get(MemcachedClient.java:1230)
	... 97 more
```
I'm using version 4.1.0 but it is not working in 4.1.2 either.

Best
smicyk

**Comment by mmoayyed** [comment]
Cool, thanks for the report. This is an easy fix. Once the patch goes it, please point your overlay to 4.1.3 SNAPSHOT and try again.

**Comment by mmoayyed** [comment]
What is this component: com.arkena.acas.services.AuthorizationBasedRegexRegisteredService?

**Comment by smicyk** [comment]
It's extends RegexRegisteredService and adds some fields (list of strings and two strings).

**Comment by mmoayyed** [comment]
What I am trying to figure out, why is a component that deals with the service registry is processed by memcached ticket registry? 

Also, your configuration is wrong. Logs indicate:

```
proxyPolicy (com.arkena.acas.services.AuthorizationBasedRegexRegisteredService)
```

Based on your description of that class, this is not a proxy policy.

**Comment by smicyk** [comment]
Without memcached ticket registry it works fine. Here is my configuration for that service:

**Comment by mmoayyed** [comment]
I see where the problem is. We'll get this fixed.

**Comment by smicyk** [comment]
Hi, I'm using version 4.1.3 to test and it seems that there is still a problem. Here is the stacktrace.

```
Caused by: java.util.concurrent.ExecutionException: com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: 95
Serialization trace:
attributes (org.jasig.cas.authentication.ImmutableAuthentication)
authentication (org.jasig.cas.ticket.TicketGrantingTicketImpl)
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:188)
	at net.spy.memcached.transcoders.TranscodeService$Task.get(TranscodeService.java:97)
	at net.spy.memcached.internal.GetFuture.get(GetFuture.java:70)
	at net.spy.memcached.MemcachedClient.get(MemcachedClient.java:1230)
	... 78 more
Caused by: com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: 95
Serialization trace:
attributes (org.jasig.cas.authentication.ImmutableAuthentication)
authentication (org.jasig.cas.ticket.TicketGrantingTicketImpl)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:137)
	at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:670)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:781)
	at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:134)
	at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:40)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:793)
	at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:161)
	at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:39)
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:711)
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:551)
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:711)
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:551)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:793)
	at org.jasig.cas.ticket.registry.support.kryo.KryoTranscoder.decode(KryoTranscoder.java:206)
	at net.spy.memcached.transcoders.TranscodeService$1.call(TranscodeService.java:63)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at net.spy.memcached.transcoders.TranscodeService$Task.run(TranscodeService.java:110)
	at net.spy.memcached.transcoders.TranscodeService$Task.get(TranscodeService.java:96)
	... 80 more
```

**Comment by mmoayyed** [comment]
You are going to have to enable DEBUG level logs for both CAS and Kryp, and investigate ` Encountered unregistered class ID: 95`

**Comment by mmoayyed** [comment]
Also it might be useful to see your ticket registry configuration.

**Comment by mmoayyed** [comment]
CAS auto-registered all classes that do not have a serializer assigned to them explicitly:
https://github.com/Jasig/cas/blob/4.1.x/cas-server-integration-memcached/src/main/java/org/jasig/cas/ticket/registry/support/kryo/KryoTranscoder.java#L178

So this seems like an issue on your side, unless you can provide more data.

**Comment by smicyk** [comment]
Here you go:

```
<bean id="ticketRegistry"
          class="org.jasig.cas.ticket.registry.MemCacheTicketRegistry"
          c:client-ref="memcachedClient"
          c:ticketGrantingTicketTimeOut="${tgt.maxTimeToLiveInSeconds}"
          c:serviceTicketTimeOut="${st.timeToKillInSeconds}" />

    <bean id="memcachedClient" class="net.spy.memcached.spring.MemcachedClientFactoryBean"
          p:servers="${memcached.servers}"
          p:protocol="${memcached.protocol}"
          p:locatorType="${memcached.locatorType}"
          p:failureMode="${memcached.failureMode}"
          p:transcoder-ref="kryoTranscoder">
        <property name="hashAlg">
            <util:constant static-field="net.spy.memcached.DefaultHashAlgorithm.${memcached.hashAlgorithm}" />
        </property>
    </bean>

    <bean id="kryoTranscoder"
          class="org.jasig.cas.ticket.registry.support.kryo.KryoTranscoder"
          init-method="initialize"
          c:initialBufferSize="8192" />
```

**Comment by mmoayyed** [comment]
Can you duplicate the problem with a fresh new instance of memcached? Can you restart the daemon?

**Comment by smicyk** [comment]
Hi,

finally I got it working. It seems that there are missing serializers for Kryo. I have to add following lines to KryoTranscoder:

```
kryo.register(LinkedHashMap.class);
kryo.register(HashSet.class);
kryo.register(UsernamePasswordCredential.class);
kryo.register(SimplePrincipal.class);
kryo.register( Collections.EMPTY_LIST.getClass(), new CollectionsEmptyListSerializer() );
kryo.register( Collections.EMPTY_MAP.getClass(), new CollectionsEmptyMapSerializer() );
kryo.register( Collections.EMPTY_SET.getClass(), new CollectionsEmptySetSerializer() );
```
What is quite strange I don't have to add serializers for my custom classes but only for those mentioned above.

I hope it helps.

**Comment by mmoayyed** [comment]
Excellent. Would you be able to submit a PR? We can include this in a 4.1.4 release for sure.

**Comment by smicyk** [comment]
Done.

**Comment by mmoayyed** [comment]
You should be able to try the patch in about 30 minutes via 4.1.4-SNAPSHOT versions.

**Comment by bb2k** [comment]
Hello it seems this bug is back in 4.1.6. (It works well in 4.1.5)

**Comment by mmoayyed** [comment]
Do you have a stacktrace you can post?

**Comment by mmoayyed** [comment]
Cross checked. I don't see any outstanding differences between 4.1.5 and 4.1.6 when it comes to handling of this issue. They are identical it seems. If you spot a difference in the code, please post back.
