### ISSUE TITLE
External log4j2.xml ignored by 4.2.0-RC3 in Tomcat

### ISSUE THREAD

**Issue by tsschmi** [Jasig/cas#1617]
When we pulled in the 4.2.0-RC3 to test with our project, we found that our log4j configuration was no longer being picked up and used by CAS.  After some digging and trying a few different things we were able to verify that changes in 4.2.0-RC3 only picked log4j2.xml in the default location of "classpath:log4j2.xml".  

We verified the issue by starting with clean maven overlay with only CAS code.  Setup cas.properties and  log4j2.xml in the default /etc/cas locations.  When we set the version to 4.2.0-RC3 our logs are not written.  If we set the version to 4.2.0-RC2 then they are present.  We tested this in tomcat7 and tomcat8.

**Comment by mmoayyed** [comment]
See https://github.com/Jasig/cas/pull/1614

**Comment by tsschmi** [comment]
Still seeing the same issue with the RC4-SNAPSHOT

**Comment by tsschmi** [comment]
This is in the Catalina logs

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/tomcat/webapps/cas/WEB-INF/lib/cas-server-core-logging-4.2.0-RC4-SNAPSHOT.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/tomcat/webapps/cas/WEB-INF/lib/log4j-slf4j-impl-2.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Attempting to locate ILoggerFactory instance from: org.apache.logging.slf4j.Log4jLoggerFactory
SLF4J: ILoggerFactory to be used for logging is: org.apache.logging.slf4j.Log4jLoggerFactory
SLF4J: Actual binding is of type [org.slf4j.impl.CasLoggerFactory]
SLF4J: The following set of substitute loggers may have been accessed
SLF4J: during the initialization phase. Logging calls during this
SLF4J: phase were not honored. However, subsequent logging calls to these
SLF4J: loggers will work as normally expected.
SLF4J: See also http://www.slf4j.org/codes.html#substituteLogger
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
SLF4J: org.reflections.Reflections

**Comment by mmoayyed** [comment]
Were u running the changes on this branch or did u actually pull the snapshot from maven repos?

**Comment by mmoayyed** [comment]
The logs you show are all normal. 

cas.properties:

```
log4j.config.location=file:///etc/cas/log4j2.xml
```

log4j2.xml:

```
<?xml version="1.0" encoding="UTF-8" ?>
<!-- Specify the refresh internal in seconds. -->
<Configuration monitorInterval="60">
    <Appenders>
        <Console name="console" target="SYSTEM_OUT">
            <PatternLayout pattern="%d %p [%c] - &lt;%m&gt;%n"/>
        </Console>
        <RollingFile name="file" fileName="cas.log" append="true"
                     filePattern="cas-%d{yyyy-MM-dd-HH}-%i.log">
            <PatternLayout pattern="%d %p [%c] - %m%n"/>
            <Policies>
                <OnStartupTriggeringPolicy />
                <SizeBasedTriggeringPolicy size="10 MB"/>
                <TimeBasedTriggeringPolicy />
            </Policies>
        </RollingFile>
        <RollingFile name="perfFileAppender" fileName="perfStats.log" append="true"
                     filePattern="perfStats-%d{yyyy-MM-dd-HH}-%i.log">
            <PatternLayout pattern="%m%n"/>
            <Policies>
                <OnStartupTriggeringPolicy />
                <SizeBasedTriggeringPolicy size="10 MB"/>
                <TimeBasedTriggeringPolicy />
            </Policies>
        </RollingFile>
    </Appenders>
    <Loggers>
        <Logger name="org.jasig" level="debug" additivity="false">
            <AppenderRef ref="console"/>
            <AppenderRef ref="file"/>
        </Logger>
        <Logger name="org.springframework" level="warn" />
        <Logger name="org.springframework.webflow" level="warn" />
        <Logger name="org.springframework.web" level="debug" />
        <Logger name="org.springframework.security" level="warn" />

        <Logger name="perfStatsLogger" level="info" additivity="false">
            <AppenderRef ref="perfFileAppender"/>
        </Logger>

        <Logger name="org.jasig.cas.web.flow" level="info" additivity="true">
            <AppenderRef ref="file"/>
        </Logger>
        <Logger name="org.jasig.inspektr.audit.support.Slf4jLoggingAuditTrailManager" level="info">
            <AppenderRef ref="file"/>
        </Logger>
        <Root level="error">
            <AppenderRef ref="console"/>
        </Root>
    </Loggers>
</Configuration>
```

Note the debug entries in the config. Start the overlay next and you will see debug entries. However, it appears that the log4j changes start too late in the process. You may lose some initial logging data. Looking into this more.

**Comment by tsschmi** [comment]
I changed the pom.xml version to 4.2.0-RC4-SNAPSHOT to test

**Comment by mmoayyed** [comment]
Could I ask you to post your overlay somewhere I could see? Because I fail to duplicate this, and you only may be seeing this if the snapshot at the time was not published. It takes about 30-40 minutes for it go out.

**Comment by tsschmi** [comment]
I tried again this morning with the force -U option to make sure the latest was resolved and it is now working as expected.  

Thanks for the help.

**Comment by mmoayyed** [comment]
Awesome. Note #1620 still exists. We are changing the way you externalize the logging config based on that patch, since today, we lose a lot of "init" logs from various components before the logging context has had a chance to init itself and take over. So Please review that one as well.
